# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luxembourg Tech School
email: info@techschool.lu
description: > # this means to ignore newlines until "baseurl:"
  The Luxembourg Tech School is an educational program aimed at 12-19 years old students who are curious about the digital realm and eager to apply technology in a real business and creative context.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.techschool.lu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

sendform_token: 36185a41482185052c0b891d07b59072

# Build settings
markdown: kramdown

# https://jekyllrb.com/docs/collections/
collections_dir: collections
collections:
    #- gamedev_videos_0_intro
    #- gamedev_videos_1_firststeps
    #- gamedev_videos_2_fastproto
    #- gamedev_videos_3_sttp
    projects:
      output: true


# CUSTOM
